### ISSUE TITLE
Use a Dockerfile / docker-compose for deployment

### ISSUE THREAD

**Issue by peey** [Abhimanyu-Jha/Events#1]
The instructions for deployment are given [here](https://github.com/Abhimanyu-Jha/Events/blob/master/Events%20setup.pdf)

The MySQL instance should persist data outside containers. In case MySQL gives any permissions problems, you could use MariaDB instead. 

Please make sure it's running on your system before sending a PR for this issue

**Comment by samber** [comment]
I'll take this one ;)
